[toolchain]
anchor_version = "0.32.1"
solana_version = "3.1.14"

[features]
resolution = true
skip-lint = false

[programs.localnet]
passkeyauth = "8tKno5VNAXXoS6pXAebh1Fhoj2C4QrRQrqFAy8nfAz7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p passkeyauth --lib"
